### ISSUE TITLE
Не могу получить результат запроса из ClickHouse, используя JavaScript

### ISSUE THREAD

**Issue by dcyrils** [apla/node-clickhouse#17]
Я только знакомлюсь как с СН, так и JS - ну, так вышло.. ((
СН подключен через @apla.
Я посылаю простейшие запросы к существующей таблице примерно так:
this.clickHouse.query ("SELECT count() FROM gStat.cand001")

На выходе получаю стрим - как и запланировано... разработчиками.
Но где мой результат (счетчик) - мне непонятно :(
Как его получить?
Спасибо

**Comment by dcyrils** [comment]
...ладно... уже не надо

**Comment by nezed** [comment]
Happy that you already found the solution)
Also you can user `.quering` method which return promise, and you can get your result by `ch.quering('SELECT 123').then(console.log)`

Voting for close this issue @apla
