### ISSUE TITLE
Define Enum type with xml config

### ISSUE THREAD

**Issue by ks-s-a** [apla/node-clickhouse#20]
Hello!

I would like to define Enum8 as an attribute type. I'v tried with this markup:

```
<attribute>
  <name>any_name</name>
  <type>Enum8('first'=1,'second'=2)</type>
  <null_value/>
</attribute>
```

but got an error:

```
Error: Unknown type Enum8('first'=1,'second'=2)
```

How could I define Enum type with xml config? I'v not found the appropriate docs.

Thanks!

**Comment by nezed** [comment]
Hi!

Please provide more info about your case and functionality.
I'm not familiar with this kind of xml configuration, probably you are talking about Dictionaries configuration.

Please pay attention! This is the driver repository, and this driver doesn't handles any chickhouse-server configurations. If its a feature request to the DBMS - you can ask about it directly in issues of https://github.com/yandex/ClickHouse/
