### ISSUE TITLE
How to import the csv file which the  columns are different with the datables table

### ISSUE THREAD

**Issue by gclinux** [apla/node-clickhouse#24]
csv file：
A,B,C,D,E
A,B,C,D,E

table：
A,E,D

**Comment by nezed** [comment]
Setting `input_format_skip_unknown_fields` to `true` may help you
https://clickhouse.yandex/docs/en/operations/settings/settings/#input-format-skip-unknown-fields

[Add this to `queryOptions`](https://github.com/apla/node-clickhouse#new-clickhouse-options)

**Comment by nezed** [comment]
Looks like solved.

**Comment by shubham696** [comment]
@gclinux how you wrote infile query. Im not able to use infile, can you post your clickhouse query you run for this
