### ISSUE TITLE
Multistatement query is not executing

### ISSUE THREAD

**Issue by AKGP** [apla/node-clickhouse#28]
I had an issue with running the multi statement query. Please provide a solution for this.

**Comment by southwolf** [comment]
Search Google. Clickhouse HTTP mode does not support multi statement.

https://groups.google.com/forum/#!topic/clickhouse/Bd-WWGhahO8
https://github.com/yandex/clickhouse-jdbc/issues/51

**Comment by nezed** [comment]
Thats right, since `node-clickhouse` uses HTTP interface, multi statement queries aren't supported.
Pay attention! Clickhouse is OLAP oriented DBMS and designed for queries with large data aggregation.

In case if you're still need to run few queries at the time, you may try following:
```sql
SELECT
  (SELECT 1) AS a,
  (SELECT 2) AS b
```
or
```js
const [a, b] = await Promise.all([
  ch.querying('SELECT 1'),
  ch.querying('SELECT 2'),
])
```
> `.querying` isn't recommended for large datasets!
