### ISSUE TITLE
How to pass the argument

### ISSUE THREAD

**Issue by gclinux** [apla/node-clickhouse#30]
clickhouse-client --input_format_allow_errors_num=1 \
--input_format_allow_errors_ratio=0.1 \
--query="INSERT INTO test.formats_test FORMAT TSV"

how to pass the --input_format_allow_errors_ratio

**Comment by nezed** [comment]
Passing those setting to `queryOptions` should help

https://github.com/apla/node-clickhouse#new-clickhouse-options
