### ISSUE TITLE
timeout is not supported

### ISSUE THREAD

**Issue by moeHaydar** [apla/node-clickhouse#31]
Currently there is no way to use the timeout option based on https://nodejs.org/api/http.html#http_http_request_options_callback

**Comment by moeHaydar** [comment]
I can submit a PR to fix it

**Comment by apla** [comment]
Sure!

**Comment by moeHaydar** [comment]
Just give me a permission to push my branch:
```ERROR: Permission to apla/node-clickhouse.git denied to moeHaydar.```
