### ISSUE TITLE
why it is complete when the err happen

### ISSUE THREAD

**Issue by gclinux** [apla/node-clickhouse#43]
// insert row data
var clickhouseStream = clickHouse.query (statement, {inputFormat: 'TSV'}, function (err) {

  console.log ('Insert complete!');

});

**Comment by gclinux** [comment]
the code is form readme

**Comment by nezed** [comment]
Looks like you do not checking for `err` argument value, nor listening for stream error.

Take a look at https://github.com/apla/node-clickhouse#selecting-large-dataset
