### ISSUE TITLE
Unable to parse CSV

### ISSUE THREAD

**Issue by chirag-20** [apla/node-clickhouse#50]
I am testing out bulk CSV inserts.
``` 
CREATE TABLE ch_test (
  `id` UInt64,
  `trans_date` DateTime,
  `sign` Int8
) ENGINE = CollapsingMergeTree(sign)
```

CSV Data:
```
1,"2019-04-17 04:15:41",1
2,"2019-04-18 04:15:41",1
3,"2019-04-19 04:15:41",1
```

Following is the error i am getting:
`Error: Cannot parse input: expected \t before: ,"2019-04-17 04:15:41",1\n2,"2019-04-18 04:15:41",1\n3,"2019-04-19 04:15:41",1\n: (at row 1)Row 1:Column 0,   name: id,         type: UInt64,   parsed text: "1"ERROR: garbage after UInt64: ",<DOUBLE QUOTE>2019-04-"(version 19.13.3.26 (official build))`

Code snippet:
```
let statement = 'INSERT INTO ch_test';
var csvStream = fs.createReadStream (csvPath);
var clickhouseStream = ch.query (statement, {inputFormat: 'CSV'});
csvStream.pipe (clickhouseStream);
```
Why is the libary forcing me to use \t(TSV) ?
Any way to resolve this using CSV?

**Comment by nezed** [comment]
There is a problem with readme because there is no `inputFormat` option in library.
#41 will help you
